export default class ActionTypes {
  static SET_USER_ROLE = 'SET_USER_ROLE';
  static SET_HOME_TOP_AD_VISIBILITY = 'SET_HOME_TOP_AD_VISIBILITY';
  static SET_HOME_BOTTOM_AD_VISIBILITY = 'SET_HOME_BOTTOM_AD_VISIBILITY';
  static SET_MOVIE_DETAILS_AD_VISIBILITY = 'SET_MOVIE_DETAILS_AD_VISIBILITY';
  static SET_SHORTS_AD_VISIBILITY = 'SET_SHORTS_AD_VISIBILITY';
  static SET_RECENT_RELEASE_AD_VISIBILITY = 'SET_RECENT_RELEASE_AD_VISIBILITY';
  static SET_SOCIAL_FEED_BOTTOM_AD_VISIBILITY =
    'SET_SOCIAL_FEED_BOTTOM_AD_VISIBILITY';
  static SET_IS_PREMIUM_USER = 'SET_IS_PREMIUM_USER';
  static IS_PREMIUM_FLOW_ENABLED = 'IS_PREMIUM_FLOW_ENABLED';
  static SET_DEFAULT_MEMBERSHIP_INFO = 'SET_DEFAULT_MEMBERSHIP_INFO';
  static RESET_COMMON_CONTEXT_STATE = 'RESET_COMMON_CONTEXT_STATE';
  static SET_BOTTOM_TAB_COMMUNITY_ID_PARAM =
    'SET_BOTTOM_TAB_COMMUNITY_ID_PARAM';
  static CREATE_COMMUNITY_FROM_PREMIUM_SCREEN =
    'CREATE_COMMUNITY_FROM_PREMIUM_SCREEN';
  static REVIEW_SEARCH_FROM_SOCIAL = 'REVIEW_SEARCH_FROM_SOCIAL';
  static IS_MUTED = 'IS_MUTED';
  static SET_SHORTS_DATA = 'SET_SHORTS_DATA';
  static SET_TRIVIA_DATA = 'SET_TRIVIA_DATA';
  static SET_IS_NEW_USER = 'SET_IS_NEW_USER';
  static SET_INITIAL_REEL_INDEX = 'SET_INITIAL_REEL_INDEX';
  static SET_TRIVIA_CAROUSEL_AD_VISIBILITY = 'SET_TRIVIA_CAROUSEL_AD_VISIBILITY';
  static LOGIN_CAROUSEL_IMAGES = 'LOGIN_CAROUSEL_IMAGES';
  static CHECK_IF_EVEN_USER_ID = 'CHECK_IF_EVEN_USER_ID';
  static SET_HAS_UNREAD_MESSAGES = 'SET_HAS_UNREAD_MESSAGES';
  
  static VIEW = 'VIEW';
  static CLICK = 'CLICK'

  static SHOW_GUEST_FLOW = 'SHOW_GUEST_FLOW';

}
